### ISSUE TITLE
Add wallet naming

### ISSUE THREAD

**Issue by stevemulligan** [ellaism/trust-wallet-ios#9]
From DesVar during wallet testing:

  Add ability to name wallets, just like in the Android version.

**Comment by vikmeup** [comment]
You can pull latest from master, it's already done on our side.

**Comment by vikmeup** [comment]
@stevemulligan I don't want you guys waste efforts on doing double work. 

Can you create PR to add your network to Trust? or just provide all the details, I will make sure to add support on iOS and Android version
- Name
- Symbol
- Decimals
- RPC Node
- Link to the explorer.

**Comment by stevemulligan** [comment]
@vikmeup This is great news!  I will work on a PR this weekend for iOS wallet.

Name: Ellaism
Symbol: ELLA
Decimals: 18
RPC Node: https://jsonrpc.ellaism.org
Explorer: https://explorer.ellaism.org

Dapp Index:  https://ellaism.github.io/trust-wallet-ios/dapps/index.html
Images Root: https://ellaism.github.io/trust-wallet-ios/images
Token Images: https://ellaism.github.io/trust-wallet-ios/images/tokens

**Comment by vikmeup** [comment]
@stevemulligan I'm going little refactor, no need to submit PR tho, will do it myself! 

Can you upload all the token images to: https://github.com/TrustWallet/tokens

**Comment by stevemulligan** [comment]
Pulled changes from upstream, this is now implemented.
